### PR TITLE
Adding iOS support

### LINKED ISSUE #1: iOS Support
Hello, is iOS support planned?
I would love to help with testing if necessary, once there's an example available

### PR DESCRIPTION
**Pull request by krispypen**
iOS support for the Unity >= 2019.3 including the project with [Unity as a Library](https://blogs.unity3d.com/2019/06/17/add-features-powered-by-unity-to-native-mobile-apps/)

gif

Fixes #1 and #10

### CODE REVIEW

**Comment by lorant-csonka-planorama** [comment]
Could you please commit this example project also?
I couldn't make it happen on iOS 😞

**Comment by thomas-stockx** [comment]
Hi @lorant-csonka-planorama,

Could you be a bit more specific about the issues you're seeing? We can always try to improve the README. I think it's more important to have clear documented steps, than a sample project that just *magically* works. Thanks!

**Comment by paolo2796** [comment]
Are there any new on AR support for iOS?

**Comment by burkard** [comment]
Hi!
Any chance to have AR support for iOS?
Thanks!!

**Pull request merged**
