### PR TITLE
Feature/unity alpha

### LINKED ISSUE #10: Official Unity Support on Native Platforms
Have you seen this? 
https://blogs.unity3d.com/2019/06/17/add-features-powered-by-unity-to-native-mobile-apps/

It's a very good news for your plugin don't you think? 
Thanks!

### PR DESCRIPTION
**Pull request by thomas-stockx**
Android support for the Unity 2019.3 new export format [Unity as a Library](https://blogs.unity3d.com/2019/06/17/add-features-powered-by-unity-to-native-mobile-apps/)

Fixes  #10 (on Android at least)

### CODE REVIEW

**Comment by juicycleff** [comment]
Thanks, @thomas-stockx reviewing the PR

**Comment by juicycleff** [comment]
@thomas-stockx I haven't tested the Unity as a Library though, but doesn't it disable the ability to embed in a section of widget or screen, since from what I've read, it forces the app to go fullscreen?

**Comment by thomas-stockx** [comment]
@juicycleff Passing an activity to the UnityPlayer forces the app to go fullscreen, which was already fixed in https://github.com/snowballdigital/flutter-unity-view-widget/pull/14.

It's independent of Unity as a Library (which is just an architectural change of the exported project, no actual code changes)

**Comment by krispypen** [comment]
Hi @juicycleff , the Unity as a Library web page indeed states:

> Unity as a Library supports full-screen rendering only; rendering on only a part of the screen is not supported

**But** that is not correct, or at least with the Flutters PlatformView solution it's perfectly possible or maybe they mean they are not really supporting it in their pro-plan... I have iOS working now, but  waiting for this PR to be merged, otherwise there is an annoying merge conflict in the README file.

**Comment by thomas-stockx** [comment]
@juicycleff Added a new example gif to the README, which was built with Unity as a Library.

**Comment by juicycleff** [comment]
Thanks, fo the feedbacks @thomas-stockx  and @krispypen and I did test it and it's working. @thomas-stockx great contribution. I will add the contributor's section today and will work on ios next this weekend I believe. Would love to see where the other contributor has gone with iOS :)

**Pull request merged**
