### PR TITLE
New example with Flutter <-> Unity communcation & iOS fixes

### LINKED ISSUE #33: how to set the pop out button in flutter unity
how to change the appearance of the popup out and title apps flutter with unity

### LINKED ISSUE #35: how to call unity functions from flutter

### LINKED ISSUE #36: how to call from unity to flutter

### LINKED ISSUE #38: Example for onUnityMessage()
Is it possible to get an example in pseudo code on how to use the onUnityMessage with Flutter and Unity? I would like to let Flutter know, when an user clicked 'Exit' in the Unity game.

### LINKED ISSUE #41: java.lang.ClassNotFoundException when sending a message from Unity to Flutter (Android)
I get this error in the debug console (Android Studio) when I send a message in Unity to Flutter.

Error:

`E/Unity   ( 8367): java.lang.ClassNotFoundException: Didn't find class "com/reactnative/unity/view/UnityUtils" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/lib/arm64, /data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/base.apk!/lib/arm64-v8a, /system/lib`

image

Code Unity:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Rotate : MonoBehaviour
{
    [SerializeField]
    //Vector3 RotateAmount;
    private float rotSpeed = 5f;

    private UnityMessageManager messanger;
    

    // Start is called before the first frame update
    void Start()
    {
        messanger = new UnityMessageManager();
    }

    private void OnMouseDrag()
    { 
        //Rotate object
        float rotX = Input.GetAxis("Mouse X") * rotSpeed * Mathf.Deg2Rad;
        transform.RotateAround(Vector3.up, -rotX);

        //send message to FLutter
        messanger.SendMessageToFlutter("Test");
    }
}
```
image

### LINKED ISSUE #56: iOS Flutter Build Build Fail
i have created a build for ios and tried to check initial build but i am getting these errors when i import the UnityMessageManager.cs class in to unity project, anyone here know how to fix this please 

Unity version 2019.3.0a4
Xcode Version 11.0 (11A420a)

`
Showing All Errors Only
Ld /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework normal armv7 (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/arpitasaxena/Downloads/flutter-unity-view-widget-master/ios/UnityExport
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target armv7-apple-ios9.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -L/Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Products/ReleaseForRunning-iphoneos -L/Users/arpitasaxena/Downloads/flutter-unity-view-widget-master/ios/UnityExport/Libraries -F/Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Products/ReleaseForRunning-iphoneos -filelist /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-armv7.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -Xlinker -dependency_info -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_dependency_info.dat -o /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework

Undefined symbols for architecture armv7:
  "_onUnityMessage", referenced from:
      _UnityMessageManager_SendMessageToFlutter_m0ADC2E517A85054AE5BA1D3328255060B20A1570 in Assembly-CSharp.o
      _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp.o
     (maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

### LINKED ISSUE #60: iOS compile fails  Undefined symbols for architecture arm64:
Hi 
i am trying get a ios build to my iphone, before this i had an error https://github.com/snowballdigital/flutter-unity-view-widget/issues/43 which i fixed by adding `- (void)frameworkWarmup:(int)argc argv:(char*[])argv;` in UnityFramework.h file but i am getting this now 

`Xcode's output:
↳
    === BUILD TARGET flutter_unity_widget OF PROJECT Pods WITH CONFIGURATION Debug ===
    Undefined symbols for architecture arm64:
      "_GetAppController", referenced from:
          -[FUController view] in FlutterUnityWidgetPlugin.o
          ___20-[FUController view]_block_invoke in FlutterUnityWidgetPlugin.o
          +[UnityUtils handleAppStateDidChange:] in UnityUtils.o
          ___27+[UnityUtils createPlayer:]_block_invoke.70 in UnityUtils.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### PR DESCRIPTION
**Pull request by thomas-stockx**
I've updated the example to include Flutter to Unity and Unity to Flutter communication so this PR
fixes #35 
fixes #36 
fixes #33 
fixes #41 

@krispypen made sure the example works on iOS, so this PR also
fixes #38 
fixes #56 
Probably also fixes #60

### CODE REVIEW

**Comment by krispypen** [comment]
### 🎉

**Comment by juicycleff** [comment]
@thomas-stockx and @krispypen you two are awesome. We can give you access too to manage stuff here, seeing how busy I am becoming

**Comment by thomas-stockx** [comment]
@juicycleff That would be nice :)

**Comment by juicycleff** [comment]
@thomas-stockx accept the invitation here https://github.com/snowballdigital/flutter-unity-view-widget/invitations

**Comment by juicycleff** [comment]
Thanks again we do appreciate it

**Comment by thomas-stockx** [comment]
Thanks man 👍

**Comment by rezajam** [comment]
I'm still having the following error:

Ld /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework normal arm64
    cd "/Users/XXXXXXX/Desktop/unity 2/flutter-unity-view-widget-master xport/example/ios/UnityExport"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos -L/Users/XXXXXXX/Desktop/unity\ 2/flutter-unity-view-widget-master\ xport/example/ios/UnityExport/Libraries -F/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos -filelist /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework

Undefined symbols for architecture arm64:
  "_onUnityMessage", referenced from:
      _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp.o
     (maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


ANY help is greatly appreciated!

**Comment by leemuljadi** [comment]
Hi @thomas-stockx,

I have added the files and the code below to send message from Unity to Flutter:
Files:
image
Code:
```
 // This method is used to send data to Flutter
 UnityMessageManager.Instance.SendMessageToFlutter("The cube feels touched.");
```
But the message still not appearing, do I actually need to edit the file in Unity and export it to Android again or I can just edit it in Android Studio in my Flutter Project?

**Comment by thomas-stockx** [comment]
Every time you make a change to the Unity project, you need to export it again.

**Comment by krunduev** [comment]
> I'm still having the following error:
> 
> Undefined symbols for architecture arm64:
> "_onUnityMessage", referenced from:
> _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp.o
> (maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ANY help is greatly appreciated!

I have too.

**Pull request merged**
